# Generated by Django 6.0.1 on 2026-02-01 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerun',
            name='map_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamerunspell',
            name='game_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='game.gamerun'),
        ),
        migrations.AlterField(
            model_name='player',
            name='coins',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='spell',
            name='effect',
            field=models.CharField(choices=[('heal', 'Heal'), ('damage', 'Damage'), ('shield', 'Shield')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userpermanentupgrade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_upgrades', to=settings.AUTH_USER_MODEL),
        ),
    ]
