# Generated by Django 6.0.1 on 2026-02-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamerun_map_level_alter_gamerunspell_game_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='max_hp',
            field=models.IntegerField(default=100),
        ),
    ]
