# Generated by Django 6.0.1 on 2026-03-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_max_hp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestItem',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='max_hp',
            new_name='base_hp',
        ),
        migrations.AddField(
            model_name='player',
            name='upgrades',
            field=models.ManyToManyField(related_name='owners', through='game.UserPermanentUpgrade', to='game.permanentupgrade'),
        ),
    ]
