# Generated by Django 6.0.1 on 2026-03-18 00:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_delete_testitem_rename_max_hp_player_base_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermanentupgrade',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
