# Generated by Django 6.0.1 on 2026-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_userpermanentupgrade_purchased_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='gamerun',
            name='enemy_attack_power',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='enemy_hp',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='gamerun',
            name='reward_coins',
            field=models.IntegerField(default=10),
        ),
    ]
