# Generated by Django 6.0.1 on 2026-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_enemy_gamerun_enemy_attack_power_gamerun_enemy_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerun',
            name='enemy_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
