# Generated by Django 6.0.1 on 2026-08-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamerun_enemy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('question_text', models.TextField()),
                ('answer_choices', models.JSONField()),
                ('correct_answer_index', models.IntegerField()),
                ('explanation', models.TextField()),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('gemini', 'Gemini')], max_length=20)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('game_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='game.gamerun')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.questions')),
            ],
        ),
    ]
