# Generated by Django 6.0.1 on 2026-08-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_seed_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionattempt',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
