# Generated by Django 6.0.1 on 2026-08-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_create_at_questionattempt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerunspell',
            name='turns_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
