# Generated by Django 6.0.1 on 2026-08-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gamerunspell_turns_remaining'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('answered_at__isnull', True)), fields=('game_run',), name='unique_active_unanswered_per_game_run'),
        ),
    ]
