# Generated by Django 6.0.1 on 2026-08-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_questionattempt_unique_active_unanswered_per_game_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerun',
            name='enemy_max_hp',
            field=models.IntegerField(default=50),
        ),
    ]
